In [34]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
df=pd.read_csv(r'C:\Users\dell\OneDrive\Desktop\dataset\Student Mental Health Analysis During Online Learning.csv')

In [35]:
df

Name  Gender  Age  Education Level  Screen Time (hrs/day)  \
0       1       1   15              6.0                    7.1   
1      16       0   25              9.0                    3.3   
2      12       1   20              2.0                    9.5   
3       2       1   20              0.0                   10.8   
4       4       0   17              4.0                    2.8   
..    ...     ...  ...              ...                    ...   
995     9       0   26              8.0                   11.3   
996     1       1   20              2.0                    5.5   
997    17       0   15              7.0                    7.1   
998    17       0   20              0.0                    4.4   
999    27       1   23              8.0                   10.8   

     Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                     8.9                           9.3           2.0   
1                     5.0                           0.2           2.0   
2                     5.4                           6.2           2.0   
3                     5.6                           5.5           0.0   
4                     5.4                           3.1           2.0   
..                    ...                           ...           ...   
995                   6.8                           9.1           2.0   
996                   6.7                           6.8           1.0   
997                   4.1                           1.9           1.0   
998                   7.5                           4.5           2.0   
999                   7.7                           3.6           1.0   

     Anxious Before Exams  Academic Performance Change  
0                       0                            2  
1                       0                            2  
2                       0                            2  
3                       1                            2  
4                       1                            2  
..                    ...                          ...  
995                     0                            2  
996                     1                            2  
997                     1                            0  
998                     0                            1  
999                     0                            1  

[1000 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Name                          1000 non-null   object 
 1   Gender                        1000 non-null   object 
 2   Age                           1000 non-null   int64  
 3   Education Level               1000 non-null   object 
 4   Screen Time (hrs/day)         1000 non-null   float64
 5   Sleep Duration (hrs)          1000 non-null   float64
 6   Physical Activity (hrs/week)  1000 non-null   float64
 7   Stress Level                  1000 non-null   object 
 8   Anxious Before Exams          1000 non-null   object 
 9   Academic Performance Change   1000 non-null   object 
dtypes: float64(3), int64(1), object(6)
memory usage: 78.3+ KB


In [36]:
df.describe()

Name       Gender          Age  Education Level  \
count  1000.00000  1000.000000  1000.000000      1000.000000   
mean     13.33400     0.575000    20.342000         5.714000   
std       8.57251     0.587128     3.459914         3.308345   
min       0.00000     0.000000    15.000000         0.000000   
25%       5.00000     0.000000    17.000000         3.000000   
50%      14.00000     1.000000    20.000000         6.000000   
75%      20.00000     1.000000    23.000000         9.000000   
max      29.00000     2.000000    26.000000        10.000000   

       Screen Time (hrs/day)  Sleep Duration (hrs)  \
count            1000.000000           1000.000000   
mean                6.909200              6.450800   
std                 2.907106              1.466407   
min                 2.000000              4.000000   
25%                 4.400000              5.100000   
50%                 6.900000              6.500000   
75%                 9.500000              7.700000   
max                12.000000              9.000000   

       Physical Activity (hrs/week)  Stress Level  Anxious Before Exams  \
count                   1000.000000    1000.00000           1000.000000   
mean                       5.017600       1.31100              0.513000   
std                        2.930344       0.75951              0.500081   
min                        0.000000       0.00000              0.000000   
25%                        2.600000       1.00000              0.000000   
50%                        5.000000       1.00000              1.000000   
75%                        7.600000       2.00000              1.000000   
max                       10.000000       2.00000              1.000000   

       Academic Performance Change  
count                  1000.000000  
mean                      1.101000  
std                       0.829148  
min                       0.000000  
25%                       0.000000  
50%                       1.000000  
75%                       2.000000  
max                       2.000000

In [37]:
df.head()

Name  Gender  Age  Education Level  Screen Time (hrs/day)  \
0     1       1   15              6.0                    7.1   
1    16       0   25              9.0                    3.3   
2    12       1   20              2.0                    9.5   
3     2       1   20              0.0                   10.8   
4     4       0   17              4.0                    2.8   

   Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                   8.9                           9.3           2.0   
1                   5.0                           0.2           2.0   
2                   5.4                           6.2           2.0   
3                   5.6                           5.5           0.0   
4                   5.4                           3.1           2.0   

   Anxious Before Exams  Academic Performance Change  
0                     0                            2  
1                     0                            2  
2                     0                            2  
3                     1                            2  
4                     1                            2

In [38]:
df.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df['Name']=le.fit_transform(df['Name'])
df['Gender']=le.fit_transform(df['Gender'])
df['Education Level']=oe.fit_transform(df[['Education Level']])
df['Stress Level']=oe.fit_transform(df[['Stress Level']])
df['Anxious Before Exams']=le.fit_transform(df['Anxious Before Exams'])
df['Academic Performance Change']=le.fit_transform(df['Academic Performance Change'])
df

Name  Gender  Age  Education Level  Screen Time (hrs/day)  \
0       1       1   15              6.0                    7.1   
1      16       0   25              9.0                    3.3   
2      12       1   20              2.0                    9.5   
3       2       1   20              0.0                   10.8   
4       4       0   17              4.0                    2.8   
..    ...     ...  ...              ...                    ...   
995     9       0   26              8.0                   11.3   
996     1       1   20              2.0                    5.5   
997    17       0   15              7.0                    7.1   
998    17       0   20              0.0                    4.4   
999    27       1   23              8.0                   10.8   

     Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                     8.9                           9.3           2.0   
1                     5.0                           0.2           2.0   
2                     5.4                           6.2           2.0   
3                     5.6                           5.5           0.0   
4                     5.4                           3.1           2.0   
..                    ...                           ...           ...   
995                   6.8                           9.1           2.0   
996                   6.7                           6.8           1.0   
997                   4.1                           1.9           1.0   
998                   7.5                           4.5           2.0   
999                   7.7                           3.6           1.0   

     Anxious Before Exams  Academic Performance Change  
0                       0                            2  
1                       0                            2  
2                       0                            2  
3                       1                            2  
4                       1                            2  
..                    ...                          ...  
995                     0                            2  
996                     1                            2  
997                     1                            0  
998                     0                            1  
999                     0                            1  

[1000 rows x 10 columns]

In [41]:
df.head()

Name  Gender  Age  Education Level  Screen Time (hrs/day)  \
0     1       1   15              6.0                    7.1   
1    16       0   25              9.0                    3.3   
2    12       1   20              2.0                    9.5   
3     2       1   20              0.0                   10.8   
4     4       0   17              4.0                    2.8   

   Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                   8.9                           9.3           2.0   
1                   5.0                           0.2           2.0   
2                   5.4                           6.2           2.0   
3                   5.6                           5.5           0.0   
4                   5.4                           3.1           2.0   

   Anxious Before Exams  Academic Performance Change  
0                     0                            2  
1                     0                            2  
2                     0                            2  
3                     1                            2  
4                     1                            2

In [42]:
df.isnull().sum()

Name                            0
Gender                          0
Age                             0
Education Level                 0
Screen Time (hrs/day)           0
Sleep Duration (hrs)            0
Physical Activity (hrs/week)    0
Stress Level                    0
Anxious Before Exams            0
Academic Performance Change     0
dtype: int64

In [43]:
df.corr()

Name    Gender       Age  Education Level  \
Name                          1.000000  0.249188  0.013762        -0.030088   
Gender                        0.249188  1.000000 -0.004262        -0.029658   
Age                           0.013762 -0.004262  1.000000         0.500895   
Education Level              -0.030088 -0.029658  0.500895         1.000000   
Screen Time (hrs/day)         0.001327 -0.060576  0.008982         0.044830   
Sleep Duration (hrs)          0.010936  0.011150 -0.010609        -0.004533   
Physical Activity (hrs/week) -0.051539  0.004643 -0.033600        -0.065284   
Stress Level                 -0.000749 -0.024299  0.007861         0.037027   
Anxious Before Exams          0.050356 -0.051054 -0.008936        -0.054624   
Academic Performance Change  -0.052633 -0.018660  0.007487        -0.004056   

                              Screen Time (hrs/day)  Sleep Duration (hrs)  \
Name                                       0.001327              0.010936   
Gender                                    -0.060576              0.011150   
Age                                        0.008982             -0.010609   
Education Level                            0.044830             -0.004533   
Screen Time (hrs/day)                      1.000000              0.011314   
Sleep Duration (hrs)                       0.011314              1.000000   
Physical Activity (hrs/week)               0.028464             -0.013407   
Stress Level                              -0.020655             -0.025524   
Anxious Before Exams                       0.025945              0.033224   
Academic Performance Change                0.036491              0.023520   

                              Physical Activity (hrs/week)  Stress Level  \
Name                                             -0.051539     -0.000749   
Gender                                            0.004643     -0.024299   
Age                                              -0.033600      0.007861   
Education Level                                  -0.065284      0.037027   
Screen Time (hrs/day)                             0.028464     -0.020655   
Sleep Duration (hrs)                             -0.013407     -0.025524   
Physical Activity (hrs/week)                      1.000000      0.003790   
Stress Level                                      0.003790      1.000000   
Anxious Before Exams                             -0.012179     -0.019879   
Academic Performance Change                      -0.008395     -0.030854   

                              Anxious Before Exams  \
Name                                      0.050356   
Gender                                   -0.051054   
Age                                      -0.008936   
Education Level                          -0.054624   
Screen Time (hrs/day)                     0.025945   
Sleep Duration (hrs)                      0.033224   
Physical Activity (hrs/week)             -0.012179   
Stress Level                             -0.019879   
Anxious Before Exams                      1.000000   
Academic Performance Change              -0.004377   

                              Academic Performance Change  
Name                                            -0.052633  
Gender                                          -0.018660  
Age                                              0.007487  
Education Level                                 -0.004056  
Screen Time (hrs/day)                            0.036491  
Sleep Duration (hrs)                             0.023520  
Physical Activity (hrs/week)                    -0.008395  
Stress Level                                    -0.030854  
Anxious Before Exams                            -0.004377  
Academic Performance Change                      1.000000

In [44]:
df.drop(['Name'],axis=1)

Gender  Age  Education Level  Screen Time (hrs/day)  \
0         1   15              6.0                    7.1   
1         0   25              9.0                    3.3   
2         1   20              2.0                    9.5   
3         1   20              0.0                   10.8   
4         0   17              4.0                    2.8   
..      ...  ...              ...                    ...   
995       0   26              8.0                   11.3   
996       1   20              2.0                    5.5   
997       0   15              7.0                    7.1   
998       0   20              0.0                    4.4   
999       1   23              8.0                   10.8   

     Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                     8.9                           9.3           2.0   
1                     5.0                           0.2           2.0   
2                     5.4                           6.2           2.0   
3                     5.6                           5.5           0.0   
4                     5.4                           3.1           2.0   
..                    ...                           ...           ...   
995                   6.8                           9.1           2.0   
996                   6.7                           6.8           1.0   
997                   4.1                           1.9           1.0   
998                   7.5                           4.5           2.0   
999                   7.7                           3.6           1.0   

     Anxious Before Exams  Academic Performance Change  
0                       0                            2  
1                       0                            2  
2                       0                            2  
3                       1                            2  
4                       1                            2  
..                    ...                          ...  
995                     0                            2  
996                     1                            2  
997                     1                            0  
998                     0                            1  
999                     0                            1  

[1000 rows x 9 columns]

In [45]:
df.rename(columns={'Gender':'Sex'})

Name  Sex  Age  Education Level  Screen Time (hrs/day)  \
0       1    1   15              6.0                    7.1   
1      16    0   25              9.0                    3.3   
2      12    1   20              2.0                    9.5   
3       2    1   20              0.0                   10.8   
4       4    0   17              4.0                    2.8   
..    ...  ...  ...              ...                    ...   
995     9    0   26              8.0                   11.3   
996     1    1   20              2.0                    5.5   
997    17    0   15              7.0                    7.1   
998    17    0   20              0.0                    4.4   
999    27    1   23              8.0                   10.8   

     Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                     8.9                           9.3           2.0   
1                     5.0                           0.2           2.0   
2                     5.4                           6.2           2.0   
3                     5.6                           5.5           0.0   
4                     5.4                           3.1           2.0   
..                    ...                           ...           ...   
995                   6.8                           9.1           2.0   
996                   6.7                           6.8           1.0   
997                   4.1                           1.9           1.0   
998                   7.5                           4.5           2.0   
999                   7.7                           3.6           1.0   

     Anxious Before Exams  Academic Performance Change  
0                       0                            2  
1                       0                            2  
2                       0                            2  
3                       1                            2  
4                       1                            2  
..                    ...                          ...  
995                     0                            2  
996                     1                            2  
997                     1                            0  
998                     0                            1  
999                     0                            1  

[1000 rows x 10 columns]

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [48]:
x=df.drop('Academic Performance Change',axis=1)
y=df['Academic Performance Change']
x

Name  Gender  Age  Education Level  Screen Time (hrs/day)  \
0       1       1   15              6.0                    7.1   
1      16       0   25              9.0                    3.3   
2      12       1   20              2.0                    9.5   
3       2       1   20              0.0                   10.8   
4       4       0   17              4.0                    2.8   
..    ...     ...  ...              ...                    ...   
995     9       0   26              8.0                   11.3   
996     1       1   20              2.0                    5.5   
997    17       0   15              7.0                    7.1   
998    17       0   20              0.0                    4.4   
999    27       1   23              8.0                   10.8   

     Sleep Duration (hrs)  Physical Activity (hrs/week)  Stress Level  \
0                     8.9                           9.3           2.0   
1                     5.0                           0.2           2.0   
2                     5.4                           6.2           2.0   
3                     5.6                           5.5           0.0   
4                     5.4                           3.1           2.0   
..                    ...                           ...           ...   
995                   6.8                           9.1           2.0   
996                   6.7                           6.8           1.0   
997                   4.1                           1.9           1.0   
998                   7.5                           4.5           2.0   
999                   7.7                           3.6           1.0   

     Anxious Before Exams  
0                       0  
1                       0  
2                       0  
3                       1  
4                       1  
..                    ...  
995                     0  
996                     1  
997                     1  
998                     0  
999                     0  

[1000 rows x 9 columns]

In [49]:
y

0      2
1      2
2      2
3      2
4      2
      ..
995    2
996    2
997    0
998    1
999    1
Name: Academic Performance Change, Length: 1000, dtype: int64

In [50]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)


In [52]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [53]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42,criterion='gini',max_depth=7,min_samples_split=5,splitter='best')
dt.fit(x_train, y_train)
y_pred=dt.predict(x_test)
print(y_pred) 

[0 1 0 2 2 1 1 0 1 1 1 2 2 1 2 1 1 0 1 2 0 1 1 1 2 2 1 1 1 2 1 1 2 1 2 2 1
 1 1 0 1 0 2 1 0 0 2 2 0 0 2 2 2 2 2 1 1 2 1 2 2 1 1 1 1 2 2 2 1 1 1 2 0 1
 2 1 2 2 2 1 0 1 2 1 0 0 2 1 1 2 2 1 1 1 0 2 2 2 1 1 2 1 2 2 2 0 2 1 2 1 1
 2 2 1 2 1 2 1 0 2 2 1 0 2 0 1 1 1 1 1 1 1 2 2 1 2 1 1 2 2 1 1 1 2 1 1 2 2
 2 0 2 2 0 0 2 2 2 1 2 0 0 2 2 2 0 0 1 2 1 2 1 0 1 2 2 2 1 2 2 1 2 0 1 2 1
 2 1 2 2 1 1 1 2 2 1 2 2 2 0 2 1 2 1 1 2 2 2 2 1 1 2 1 2 1 1 2 2 0 2 1 1 2
 1 1 2 2 1 1 2 1 2 2 2 2 1 0 1 0 1 1 2 0 1 1 1 1 1 2 2 1 2 2 2 2 2 2 1 2 2
 0 2 2 0 2 1 2 2 1 2 1 2 1 1 0 2 2 0 2 2 2 0 1 0 2 1 1 0 1 2 2 2 1 0 1 2 1
 0 2 2 0]


In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.36
              precision    recall  f1-score   support

           0       0.36      0.18      0.24        89
           1       0.34      0.43      0.38        95
           2       0.38      0.44      0.41       116

    accuracy                           0.36       300
   macro avg       0.36      0.35      0.34       300
weighted avg       0.36      0.36      0.35       300

[[16 32 41]
 [11 41 43]
 [17 48 51]]


In [55]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42,criterion='gini',max_depth=7,min_samples_split=5,splitter='best')
dt.fit(x_test, y_test)
y_pred=dt.predict(x_test)
print(y_pred) 

[0 1 1 2 1 0 2 1 2 2 0 0 1 1 1 2 1 2 2 1 0 2 1 2 1 0 1 2 1 2 1 0 0 2 0 1 2
 2 1 1 2 1 1 1 1 2 1 2 2 2 1 1 0 1 1 2 1 1 0 2 0 0 1 2 0 2 2 1 2 2 1 1 0 0
 2 0 1 2 1 0 0 0 2 1 1 2 0 2 0 2 2 2 2 2 1 1 2 2 1 0 2 2 2 1 2 1 0 1 1 1 1
 1 2 0 1 2 0 2 0 0 1 2 0 2 0 0 1 2 2 1 1 2 0 1 0 0 0 2 2 1 2 0 2 0 2 2 2 2
 2 2 2 1 2 0 1 1 2 1 0 0 1 2 0 2 0 0 1 1 2 0 1 1 2 0 1 2 1 0 0 1 2 2 0 2 2
 2 2 1 1 1 2 0 0 2 2 1 1 1 0 1 2 2 0 0 1 2 1 2 2 1 0 2 1 2 0 0 2 2 2 2 2 2
 0 0 2 0 2 1 1 2 1 0 1 2 1 0 0 2 2 1 1 2 1 2 2 1 0 1 1 2 2 1 1 0 1 0 2 1 0
 2 1 1 2 1 1 1 2 1 2 0 2 2 1 0 1 2 0 2 2 0 2 2 2 1 2 2 0 1 1 1 1 2 0 0 2 2
 2 2 1 0]


In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.6766666666666666
              precision    recall  f1-score   support

           0       0.72      0.60      0.65        89
           1       0.63      0.69      0.66        95
           2       0.69      0.72      0.71       116

    accuracy                           0.68       300
   macro avg       0.68      0.67      0.67       300
weighted avg       0.68      0.68      0.68       300

[[53 19 17]
 [ 9 66 20]
 [12 20 84]]


In [62]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train, y_train)
y_pred=lr.predict(x_test)
print(y_pred) 

[1 2 2 2 2 2 0 1 1 1 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 2 2 2 2
 1 1 2 1 2 2 2 2 2 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 0 0 0 1 2 2 1 2 2 1 2 2 2 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2
 2 2 0 2 1 2 1 2 0 2 2 2 2 2 2 1 2 2 2 1 1 2 2 2 2 2 1 2 2 2 2 2 2 1 2 1 2
 2 2 2 2 1 0 0 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 0 2 2 2
 2 1 2 1 2 2 1 2 2 2 2 2 2 2 2 1 2 2 0 2 2 1 2 2 1 2 1 2 2 2 2 2 2 2 1 2 2
 2 2 2 2 1 2 2 1 1 2 2 1 2 0 1 2 2 2 2 1 1 2 1 2 2 2 2 2 0 2 2 2 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 1 2 0 2 2 2 2 2 2 1 2 2 2 1
 2 2 2 2]


In [63]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.37333333333333335
              precision    recall  f1-score   support

           0       0.42      0.09      0.15        89
           1       0.33      0.17      0.22        95
           2       0.38      0.76      0.51       116

    accuracy                           0.37       300
   macro avg       0.38      0.34      0.29       300
weighted avg       0.37      0.37      0.31       300

[[ 8 13 68]
 [ 3 16 76]
 [ 8 20 88]]


In [64]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test, y_test)
y_pred=lr.predict(x_test)
print(y_pred) 

[2 2 2 1 2 2 2 2 2 1 1 0 1 1 2 2 2 0 1 2 2 1 0 2 2 0 1 2 2 2 2 2 2 2 1 1 1
 2 2 2 2 1 1 2 0 2 2 2 2 2 2 1 2 1 2 2 2 1 2 2 1 2 0 0 2 2 2 2 1 0 0 0 0 1
 2 2 0 2 1 2 2 2 2 2 2 2 2 0 2 2 2 0 2 2 0 1 2 2 2 2 2 2 0 0 0 1 2 1 1 2 2
 2 2 2 2 2 2 2 1 0 0 2 2 2 0 2 1 2 2 2 2 2 2 2 2 0 0 2 1 1 2 2 2 0 2 1 1 1
 2 2 0 2 2 2 2 2 0 0 0 2 2 0 2 1 2 1 0 2 2 2 2 2 1 1 0 2 1 2 0 2 2 2 0 2 0
 1 2 2 2 2 2 2 2 2 2 0 1 1 2 1 0 2 2 2 2 1 0 1 2 0 1 2 2 2 1 0 1 2 2 2 2 2
 2 2 2 1 2 2 1 2 2 0 2 1 1 0 0 2 2 2 1 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 1 1 2
 2 1 2 2 2 0 0 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 1 2 1 0 2 2 0 2 2 2
 2 2 1 1]


In [65]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.41
              precision    recall  f1-score   support

           0       0.37      0.20      0.26        89
           1       0.44      0.26      0.33        95
           2       0.41      0.69      0.52       116

    accuracy                           0.41       300
   macro avg       0.41      0.39      0.37       300
weighted avg       0.41      0.41      0.38       300

[[18 15 56]
 [12 25 58]
 [19 17 80]]


In [66]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
print(y_pred) 

[1 0 2 2 0 2 0 1 1 1 2 0 0 2 2 1 1 2 2 0 2 2 0 2 0 2 0 2 1 2 0 1 2 2 0 2 2
 1 1 2 2 2 2 1 0 1 0 2 1 1 0 2 0 2 0 0 2 1 1 2 2 2 1 1 2 2 0 2 2 1 2 0 0 2
 2 1 1 2 2 0 0 0 2 2 2 2 2 1 0 0 2 0 1 0 1 0 0 2 1 0 1 0 2 2 0 2 0 2 2 2 2
 2 2 2 2 1 2 2 0 2 2 0 1 2 0 1 1 0 2 2 1 1 0 2 2 0 1 1 2 0 1 0 0 2 1 1 2 2
 1 2 1 2 2 0 2 2 2 2 1 0 2 2 2 2 0 0 2 2 1 2 1 0 2 0 2 2 1 2 1 2 1 0 0 2 2
 2 1 0 1 2 2 2 2 2 2 1 2 1 0 1 1 2 2 0 2 2 2 2 2 1 0 1 2 0 2 2 1 0 2 1 0 2
 1 2 1 2 2 1 0 1 2 0 2 1 2 0 1 1 1 2 2 1 0 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 0
 0 1 0 2 2 2 2 2 1 2 2 2 2 0 2 2 2 0 1 1 2 1 1 1 2 0 0 2 2 1 2 0 1 2 2 2 1
 2 2 0 2]


In [67]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.36666666666666664
              precision    recall  f1-score   support

           0       0.30      0.25      0.27        89
           1       0.39      0.31      0.34        95
           2       0.39      0.51      0.44       116

    accuracy                           0.37       300
   macro avg       0.36      0.35      0.35       300
weighted avg       0.36      0.37      0.36       300

[[22 16 51]
 [23 29 43]
 [28 29 59]]


In [68]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_test, y_test)
y_pred=rf.predict(x_test)
print(y_pred) 

[1 2 0 2 2 2 2 1 0 2 0 0 1 1 1 2 1 2 2 2 0 1 1 2 1 2 1 1 1 0 1 0 2 2 0 1 1
 1 1 2 2 1 2 1 2 2 2 2 0 2 2 1 0 1 1 2 1 1 1 2 0 1 1 2 0 2 2 0 2 2 2 0 0 0
 2 0 1 2 1 0 2 0 2 2 1 2 0 2 0 2 1 2 2 2 2 0 2 2 1 1 1 2 2 1 2 1 0 1 1 1 2
 0 0 0 0 1 0 2 0 0 1 2 2 2 0 1 0 0 2 1 1 0 0 0 0 1 0 0 2 1 2 0 1 0 2 2 2 2
 2 0 2 0 2 2 1 0 2 1 0 2 1 0 0 2 0 0 2 0 1 0 1 1 2 1 2 2 1 2 0 1 1 2 2 2 2
 0 2 1 1 1 0 0 0 2 2 2 1 2 1 1 0 2 0 0 0 1 1 2 2 1 0 2 0 2 0 0 1 1 2 1 2 2
 0 0 2 0 1 1 1 2 1 0 1 2 2 0 0 2 2 1 1 0 1 0 2 0 0 1 0 0 2 1 0 0 1 2 2 0 2
 2 2 1 1 1 1 2 2 1 1 0 2 2 1 0 0 1 2 2 0 1 1 2 0 1 2 1 0 2 1 0 1 2 0 0 2 2
 2 2 1 0]


In [69]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        89
           1       1.00      1.00      1.00        95
           2       1.00      1.00      1.00       116

    accuracy                           1.00       300
   macro avg       1.00      1.00      1.00       300
weighted avg       1.00      1.00      1.00       300

[[ 89   0   0]
 [  0  95   0]
 [  0   0 116]]


In [70]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.naive_bayes import GaussianNB
gn=GaussianNB()
gn.fit(x_train, y_train)
y_pred=gn.predict(x_test)
print(y_pred) 

[1 2 2 2 2 1 2 1 1 1 2 2 2 2 2 1 1 1 2 2 2 2 2 1 2 2 2 2 2 2 2 1 0 2 2 2 2
 1 1 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 0 0 0 1 2 2 1 2 2 1 2 2 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2
 2 2 0 2 0 2 1 2 0 2 2 2 2 2 2 1 2 2 2 1 1 2 2 2 2 2 1 1 2 2 2 2 2 1 2 1 2
 2 2 2 2 1 0 2 2 2 2 2 2 2 2 1 2 2 2 2 2 0 2 2 0 2 2 2 1 2 2 2 2 2 0 2 2 2
 2 1 2 1 2 1 1 2 2 2 2 2 1 2 2 1 2 2 2 2 2 1 2 0 1 2 1 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 1 2 2 1 2 1 2 1 2 0 1 2 2 2 2 1 1 2 1 2 2 2 2 2 0 2 2 2 0 2 2 2 2
 2 2 2 1 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 1
 2 2 2 2]


In [71]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.3466666666666667
              precision    recall  f1-score   support

           0       0.31      0.06      0.10        89
           1       0.25      0.15      0.19        95
           2       0.37      0.73      0.49       116

    accuracy                           0.35       300
   macro avg       0.31      0.31      0.26       300
weighted avg       0.32      0.35      0.28       300

[[ 5 16 68]
 [ 5 14 76]
 [ 6 25 85]]


In [72]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.3, random_state=50)
from sklearn.naive_bayes import GaussianNB
gn=GaussianNB()
gn.fit(x_test, y_test)
y_pred=gn.predict(x_test)
print(y_pred) 

[2 2 2 1 2 1 2 2 2 1 1 0 1 1 1 1 2 1 1 2 0 1 0 2 2 0 2 2 2 2 2 2 2 2 1 1 1
 2 2 1 2 1 0 2 0 2 2 1 0 2 2 1 2 1 2 2 2 1 2 2 1 2 0 2 2 2 2 2 2 0 0 0 0 1
 2 2 0 0 1 2 2 2 1 2 2 2 2 0 2 2 2 2 2 2 0 1 2 2 2 2 2 2 0 0 0 1 2 1 1 2 2
 2 2 2 2 2 0 2 0 2 2 2 2 2 0 2 1 2 2 1 2 2 2 2 1 0 0 2 2 2 2 2 2 1 2 1 1 1
 2 2 0 2 2 2 0 2 0 0 0 2 2 0 2 1 2 1 0 2 2 2 2 2 1 1 0 2 1 2 0 2 2 2 2 2 0
 1 2 2 1 2 2 2 2 2 2 2 1 1 2 1 2 0 2 2 2 1 0 1 2 0 1 2 2 2 1 0 1 2 2 2 2 2
 2 0 0 0 1 2 1 2 1 0 2 1 1 0 0 2 2 2 1 0 1 2 0 2 2 2 2 2 2 0 2 2 2 0 1 1 2
 2 1 2 2 0 0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 1 2 1 0 2 2 0 2 2 2
 2 2 2 1]


In [73]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.42
              precision    recall  f1-score   support

           0       0.42      0.25      0.31        89
           1       0.44      0.29      0.35        95
           2       0.42      0.66      0.51       116

    accuracy                           0.42       300
   macro avg       0.42      0.40      0.39       300
weighted avg       0.42      0.42      0.40       300

[[22 15 52]
 [12 28 55]
 [19 21 76]]


In [81]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
from sklearn.model_selection import KFold,cross_val_score
kf=KFold(n_splits=7,random_state=42,shuffle=True)
scores=cross_val_score(knn,x,y,cv=kf)
print(scores)

[0.30769231 0.37762238 0.34265734 0.32867133 0.28671329 0.32167832
 0.25352113]


In [82]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=7,random_state=42,shuffle=True)
for train_index,test_index in kf.split(x):
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]
    knn.fit(x_train,y_train)
    y_pred=knn.predict(x_test)
    print(accuracy_score(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))

0.3076923076923077
              precision    recall  f1-score   support

           0       0.25      0.32      0.28        41
           1       0.30      0.28      0.29        46
           2       0.37      0.32      0.34        56

    accuracy                           0.31       143
   macro avg       0.31      0.31      0.31       143
weighted avg       0.31      0.31      0.31       143

[[13 17 11]
 [13 13 20]
 [25 13 18]]
0.3776223776223776
              precision    recall  f1-score   support

           0       0.32      0.36      0.34        47
           1       0.29      0.40      0.34        35
           2       0.55      0.38      0.45        61

    accuracy                           0.38       143
   macro avg       0.39      0.38      0.37       143
weighted avg       0.41      0.38      0.38       143

[[17 15 15]
 [17 14  4]
 [19 19 23]]
0.34265734265734266
              precision    recall  f1-score   support

           0       0.33      0.42      0.37        

In [83]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=7,random_state=42,shuffle=True)
for train_index,test_index in kf.split(x):
    x_train,x_test=x[train_index],x[test_index]
    y_train,y_test=y[train_index],y[test_index]
    knn.fit(x_test,y_test)
    y_pred=knn.predict(x_test)
    print(accuracy_score(y_test,y_pred))
    print(classification_report(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))

0.5664335664335665
              precision    recall  f1-score   support

           0       0.43      0.63      0.51        41
           1       0.63      0.57      0.60        46
           2       0.69      0.52      0.59        56

    accuracy                           0.57       143
   macro avg       0.59      0.57      0.57       143
weighted avg       0.60      0.57      0.57       143

[[26  6  9]
 [16 26  4]
 [18  9 29]]
0.5524475524475524
              precision    recall  f1-score   support

           0       0.47      0.60      0.52        47
           1       0.57      0.49      0.52        35
           2       0.64      0.56      0.60        61

    accuracy                           0.55       143
   macro avg       0.56      0.55      0.55       143
weighted avg       0.57      0.55      0.55       143

[[28  5 14]
 [13 17  5]
 [19  8 34]]
0.6153846153846154
              precision    recall  f1-score   support

           0       0.62      0.74      0.67        4